project:
  type: website
  output-dir: docs

website:
  title: "Intro to R for School Finance Equity, PIE Summit 2023"
  sidebar:
    background: primary
    logo: "images/primary_one-color_reverse.png"
    pinned: true
    style: docked
    contents:
      - href: index.qmd
        text: Home
      - href: setup.qmd
        text: Setup
      - href: scripts.qmd
        text: Scripts
     
format:
  html:
    theme: 
      - cosmo
      - theme/site_format.scss
    toc: true


    
    
    