project:
  type: website
  output-dir: docs

website:
  title: "Quantitative Peer Learning Community R Training"
  sidebar:
    background: primary
    logo: "images/primary_one-color_reverse.png"
    pinned: true
    style: docked
    contents:
      - href: index.qmd
        text: Home
      - href: setup.qmd
        text: Setup
      - href: schedule.qmd
        text: Schedule
     
format:
  html:
    theme: 
      - cosmo
      - theme/site_format.scss
    toc: true


    
    
    