---
title: "Quantitative Peer Learning Community R Training"
format: html
---

## About this R training

There has been a growing demand amongst Bellwarians to learn R to support them in data cleaning, analysis and visualization. To support Bellwarians in developing their R skills, the Quantitaive PLC is providing a 9 week course that will teach them how to do the following:

-   Data cleaning and analysis

-   Join two or more data frames

-   Advanced data visualizations, including charts, graphs, and maps

-   Create high-quality presentations using Quarto

## R Class Prep

Prior to the first class on March 19, participants should do the following:

-   **Install R, RStudio, and specified packages**. Detailed [instructions for downloading required software are available here](https://kkaput23.github.io/quant_plc/setup.html).

-   **Create a Github account**. Detailed instructions for how to set up a [Github account can be found here](https://docs.github.com/en/get-started/start-your-journey/creating-an-account-on-github).

-   Download R packages

## Instructors

-   [Krista Kaput](https://bellwether.org/experts/krista-kaput/)

-   [Alex Spurrier](https://bellwether.org/experts/alex-spurrier/)
